[package]
name = "image_screen"
version = "0.1.0"
edition = "2024"


[dependencies]
eframe = "0.31.1"
# Async, futures
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", features = ["stream"] }
flume = "0.10"
image = "0.24"
# For image support:
egui_extras = { version = "0.31.1", features = ["default", "image"] }
# Logging
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
crossbeam = "0.8.4"
